# Generated by Django 4.2.4 on 2024-11-08 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imongu_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_stripe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_stripe_id', models.CharField(max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(null=True)),
                ('free_trial_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
