# Generated by Django 4.2.4 on 2024-11-08 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imongu_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notify_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('notification', models.TextField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('isDeleted', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('notify_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notifications')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
        ),
    ]
