# Generated by Django 4.2.4 on 2024-11-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='imongu_backend_app.employee'),
        ),
    ]
