# Generated by Django 4.2.4 on 2024-11-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0002_employee_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='imongu_backend_app.role'),
        ),
    ]
