# Generated by Django 4.2.4 on 2024-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0003_role_parent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
