# Generated by Django 4.2.4 on 2024-11-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0004_alter_okr_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='parent_role',
        ),
    ]
