# Generated by Django 4.2.4 on 2024-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0006_goal_asana_project_id_key_results_asana_subtask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
