# Generated by Django 4.2.4 on 2024-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0007_user_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBookContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ebook_contact',
            },
        ),
    ]
