# Generated by Django 4.2.4 on 2024-11-28 08:56

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0008_ebookcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookcontact',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebookcontact',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebookcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ebookcontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ebookcontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ebookcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
