# Generated by Django 4.2.4 on 2024-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0009_alter_ebookcontact_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
