# Generated by Django 4.2.4 on 2024-12-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0010_employee_deactivated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deactivated',
        ),
    ]
