# Generated by Django 4.2.4 on 2024-11-08 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imongu_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('board_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
            options={
                'db_table': 'trello',
            },
        ),
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=255)),
                ('expiry', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
            options={
                'db_table': 'google_token',
            },
        ),
    ]
