# Generated by Django 4.2.4 on 2024-11-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trelloconnection',
            old_name='company_id',
            new_name='company',
        ),
    ]
