# Generated by Django 4.2.4 on 2024-11-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0005_remove_role_parent_role'),
        ('integrations', '0002_rename_company_id_trelloconnection_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
            options={
                'db_table': 'asana_connection',
            },
        ),
    ]
