# Generated by Django 4.2.4 on 2024-11-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_asanaconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asanaconnection',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='connection_name',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='asanaconnection',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='asanaconnection',
            table=None,
        ),
    ]
