# Generated by Django 4.2.4 on 2024-11-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_remove_asanaconnection_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asanaconnection',
            table='asana_connection',
        ),
    ]
