# Generated by Django 4.2.4 on 2024-11-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imongu_backend_app', '0006_goal_asana_project_id_key_results_asana_subtask_id_and_more'),
        ('integrations', '0005_alter_asanaconnection_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expiry', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imongu_backend_app.user')),
            ],
            options={
                'db_table': 'microsoft_token',
            },
        ),
    ]
